// Monaco 英文→中文映射表。键必须与 monaco-editor esm 源码中 localize/localize2 的
// 英文默认值逐字符一致(含 {0} 占位符、撇号、行尾空格),查不到的键自动回落英文。
// 覆盖范围:v0.1 全部用户可见面(查找替换/补全/悬停/快速修复/右键菜单/F1 命令面板/
// 问题导航/折叠/注释/多光标/重命名/格式化/缩进/颜色选择器/Unicode 高亮对话框/粘滞滚动等)。
// 不可见面(主题色描述、纯无障碍长文、上下文键调试描述)不翻译。
export const ZH_TABLE: Record<string, string> = {
  // ===== 快速修复 / 代码操作 =====
  'No quick fixes available': '没有可用的快速修复',
  'Checking for quick fixes...': '正在查找快速修复…',
  'Quick Fix': '快速修复',
  'Quick Fix...': '快速修复…',
  'Auto Fix...': '自动修复…',
  'Fix All': '全部修复',
  'No auto fixes available': '没有可用的自动修复',
  'No fix all action available': '没有可用的“全部修复”操作',
  'No code actions available': '没有可用的代码操作',
  "No code actions for '{0}' available": '“{0}”没有可用的代码操作',
  'No preferred code actions available': '没有首选的代码操作',
  "No preferred code actions for '{0}' available": '“{0}”没有首选的代码操作',
  'Refactor...': '重构…',
  'No refactorings available': '没有可用的重构操作',
  "No refactorings for '{0}' available": '“{0}”没有可用的重构操作',
  'No preferred refactorings available': '没有首选的重构操作',
  "No preferred refactorings for '{0}' available": '“{0}”没有首选的重构操作',
  'Source Action': '源代码操作',
  'Source Action...': '源代码操作…',
  'No source actions available': '没有可用的源代码操作',
  "No source actions for '{0}' available": '“{0}”没有可用的源代码操作',
  'No preferred source actions available': '没有首选的源代码操作',
  "No preferred source actions for '{0}' available": '“{0}”没有首选的源代码操作',
  'Organize Imports': '整理导入',
  'No organize imports action available': '没有可用的“整理导入”操作',
  'Show Code Actions': '显示代码操作',
  'Show Code Actions ({0})': '显示代码操作 ({0})',
  'Show Code Actions. Preferred Quick Fix Available ({0})': '显示代码操作。有首选快速修复 ({0})',
  'An unknown error occurred while applying the code action': '应用代码操作时发生未知错误',
  "Error applying edit '{0}':\n{1}": "应用编辑“{0}”时出错:\n{1}",
  "Error resolving edit '{0}':\n{1}": "解析编辑“{0}”时出错:\n{1}",
  Extract: '提取',
  Rewrite: '重写',
  Fill: '填充',
  'Surround With': '环绕',

  // ===== 悬停 =====
  'Loading...': '正在加载…',
  'Increase Hover Verbosity': '增加悬停详细程度',
  'Decrease Hover Verbosity': '降低悬停详细程度',
  'Increase Hover Verbosity ({0})': '增加悬停详细程度 ({0})',
  'Decrease Hover Verbosity ({0})': '降低悬停详细程度 ({0})',
  'Hold {0} key to mouse over': '按住 {0} 键悬停查看',
  'alt + click': 'alt + 点击',
  'ctrl + click': 'ctrl + 点击',
  'cmd + click': 'cmd + 点击',
  'option + click': 'option + 点击',
  'Mouse Over': '鼠标悬停',
  'Show or focus the editor hover which shows documentation, references, and other content for a symbol at the current cursor position.':
    '显示或聚焦编辑器悬停，显示当前光标处符号的文档、引用等内容。',

  // ===== 问题导航 =====
  'View Problem': '查看问题',
  'Go to Next Problem (Error, Warning, Info)': '转到下一个问题(错误、警告、信息)',
  'Go to Previous Problem (Error, Warning, Info)': '转到上一个问题(错误、警告、信息)',
  'Go to Next Problem in Files (Error, Warning, Info)': '转到下个文件中的问题(错误、警告、信息)',
  'Go to Previous Problem in Files (Error, Warning, Info)': '转到上个文件中的问题(错误、警告、信息)',
  '{0} of {1} problem': '第 {0} 个，共 {1} 个问题',
  '{0} of {1} problems': '第 {0} 个，共 {1} 个问题',
  Error: '错误',
  Warning: '警告',
  Info: '信息',
  Hint: '提示',
  'Error: {0}': '错误: {0}',
  'Info: {0}': '信息: {0}',
  'Warning: {0}': '警告: {0}',

  // ===== 查找 / 替换 =====
  Find: '查找',
  Replace: '替换',
  'Find / Replace': '查找/替换',
  'Find Next': '查找下一个',
  'Find Previous': '查找上一个',
  'Next Match': '下一个匹配',
  'Previous Match': '上一个匹配',
  'Find Next Selection': '查找下一个选定内容',
  'Find Previous Selection': '查找上一个选定内容',
  'Find With Selection': '查找选定内容',
  'Find With Arguments': '查找(带参数)',
  'Find in Selection': '在选定内容中查找',
  'Toggle Replace': '切换替换',
  'Replace All': '全部替换',
  'Match Case': '区分大小写',
  'Match Whole Word': '全字匹配',
  'Use Regular Expression': '使用正则表达式',
  'Preserve Case': '保留大小写',
  '{0} found': '找到 {0} 个',
  '{0} results': '{0} 个结果',
  'No results': '无结果',
  'No results found': '未找到结果',
  'No matches. Try searching for something else.': '无匹配。请尝试其他搜索内容。',
  'Only the first {0} results are highlighted, but all find operations work on the entire text.':
    '仅高亮前 {0} 个结果，但所有查找操作都作用于整个文本。',
  'The file is too large to perform a replace all operation.': '文件过大，无法执行全部替换操作。',
  'Ctrl+Enter now inserts line break instead of replacing all. You can modify the keybinding for editor.action.replaceAll to override this behavior.':
    'Ctrl+Enter 现在会插入换行符而不是全部替换。可修改 editor.action.replaceAll 的键绑定来更改此行为。',
  'Type a number to go to a specific match (between 1 and {0})': '输入数字以转到特定匹配(1 到 {0} 之间)',

  // ===== 建议(补全) =====
  'No suggestions.': '无建议。',
  Suggest: '建议',
  'Trigger Suggest': '触发建议',
  'Trigger Parameter Hints': '触发参数提示',
  Insert: '插入',
  'Read More': '阅读更多',
  'Show More': '显示更多',
  'Show Less': '显示更少',
  'Reset Suggest Widget Size': '重置建议组件大小',
  'Vertical size': '垂直大小',
  'Fuzzy Match': '模糊匹配',
  'Suggestion:': '建议:',
  Accept: '接受',
  'Accept Word': '接受词',
  'Accept Line': '接受行',
  'methods ({0})': '方法 ({0})',
  'functions ({0})': '函数 ({0})',
  'constructors ({0})': '构造函数 ({0})',
  'fields ({0})': '字段 ({0})',
  'variables ({0})': '变量 ({0})',
  'classes ({0})': '类 ({0})',
  'structs ({0})': '结构 ({0})',
  'interfaces ({0})': '接口 ({0})',
  'modules ({0})': '模块 ({0})',
  'properties ({0})': '属性 ({0})',
  'events ({0})': '事件 ({0})',
  'operators ({0})': '运算符 ({0})',
  'namespaces ({0})': '命名空间 ({0})',
  'packages ({0})': '包 ({0})',
  'type parameters ({0})': '类型参数 ({0})',
  'constants ({0})': '常量 ({0})',
  'enumerations ({0})': '枚举 ({0})',
  'enumeration members ({0})': '枚举成员 ({0})',
  'strings ({0})': '字符串 ({0})',
  'numbers ({0})': '数字 ({0})',
  'booleans ({0})': '布尔 ({0})',
  'objects ({0})': '对象 ({0})',
  'keys ({0})': '键 ({0})',
  'arrays ({0})': '数组 ({0})',
  'files ({0})': '文件 ({0})',
  'symbols ({0})': '符号 ({0})',

  // ===== 内联建议 / 内联编辑 =====
  'Accept Inline Suggestion': '接受内联建议',
  'Accept Inline Edit': '接受内联编辑',
  'Accept Next Line Of Inline Suggestion': '接受内联建议的下一行',
  'Accept Next Word Of Inline Suggestion': '接受内联建议的下一个词',
  'Hide Inline Suggestion': '隐藏内联建议',
  'Hide Inline Edit': '隐藏内联编辑',
  'Show Next Inline Suggestion': '显示下一个内联建议',
  'Show Previous Inline Suggestion': '显示上一个内联建议',
  'Show Next Inline Edit': '显示下一个内联编辑',
  'Show Previous Inline Edit': '显示上一个内联编辑',
  'Trigger Inline Suggestion': '触发内联建议',
  'Trigger Inline Edit': '触发内联编辑',
  Pin: '固定',
  Unpin: '取消固定',
  'Pin Inline Edit': '固定内联编辑',
  'Always Show Toolbar': '始终显示工具栏',
  "Accepting '{0}' made {1} additional edits": '接受“{0}”产生了 {1} 个额外编辑',

  // ===== 跳转 / 速览 / 符号 =====
  'Go to Definition': '转到定义',
  'Go to Definition ({0})': '转到定义 ({0})',
  'Go to Definition ({0}), right click for more': '转到定义 ({0})，右键查看更多',
  'Open Definition to the Side': '在侧边打开定义',
  Peek: '速览',
  'Peek Definition': '速览定义',
  'Peek Declaration': '速览声明',
  'Peek Implementations': '速览实现',
  'Peek References': '速览引用',
  'Peek Type Definition': '速览类型定义',
  'Go to Declaration': '转到声明',
  'Go to References': '转到引用',
  'Go to Type Definition': '转到类型定义',
  'Go to Implementations': '转到实现',
  'Open to the Side': '在侧边打开',
  'Open to the Bottom': '在底部打开',
  'No definition found': '未找到定义',
  "No definition found for '{0}'": '未找到“{0}”的定义',
  'No declaration found': '未找到声明',
  "No declaration found for '{0}'": '未找到“{0}”的声明',
  'No references found': '未找到引用',
  "No references found for '{0}'": '未找到“{0}”的引用',
  'No implementation found': '未找到实现',
  "No implementation found for '{0}'": '未找到“{0}”的实现',
  'No type definition found': '未找到类型定义',
  "No type definition found for '{0}'": '未找到“{0}”的类型定义',
  References: '引用',
  Declarations: '声明',
  Definitions: '定义',
  Implementations: '实现',
  'Type Definitions': '类型定义',
  Locations: '位置',
  '{0} reference': '{0} 个引用',
  '{0} references': '{0} 个引用',
  "{0} found for '{1}'": '为“{1}”找到 {0} 个',
  "{0} found for '{1}', at {2}": '为“{1}”找到 {0} 个，位于 {2}',
  '1 symbol in {0}, full path {1}': '{0} 中有 1 个符号，完整路径 {1}',
  'Found 1 symbol in {0}': '在 {0} 中找到 1 个符号',
  'Found {0} symbols in {1}': '在 {1} 中找到 {0} 个符号',
  'Found {0} symbols in {1} files': '在 {1} 个文件中找到 {0} 个符号',
  '{0} symbols in {1}, full path {2}': '{1} 中有 {0} 个符号，完整路径 {2}',
  'Click to show {0} definitions.': '点击显示 {0} 个定义。',
  'Symbol {0} of {1}': '符号 {0}/{1}',
  'Symbol {0} of {1}, {2} for next': '符号 {0}/{1}，按 {2} 看下一个',
  'no preview available': '无预览',
  'in {0} on line {1} at column {2}': '位于 {0} 第 {1} 行第 {2} 列',
  '{0} at {1}. ': '{0} 位于 {1}。 ',
  'Go to Any Symbol': '转到任意符号',
  'Go to Symbol...': '转到符号…',
  'Go to Symbol by Category...': '按类别转到符号…',
  'Go to Bracket': '转到括号',
  'Select to Bracket': '选至括号',
  'Go to Match...': '转到匹配…',
  'Select the text inside and including the brackets or curly braces': '选择括号或花括号内(含括号)的文本',
  'No editor symbols': '无编辑器符号',
  'No matching editor symbols': '无匹配的编辑器符号',
  'To go to a symbol, first open a text editor with symbol information.': '要跳转符号，请先打开包含符号信息的文本编辑器。',
  'The active text editor does not provide symbol information.': '当前文本编辑器未提供符号信息。',
  'Go to Next Symbol Highlight': '转到下一个符号高亮',
  'Go to Previous Symbol Highlight': '转到上一个符号高亮',
  'Trigger Symbol Highlight': '触发符号高亮',

  // ===== 行跳转 =====
  'Go to Line/Column...': '转到行/列…',
  'Go to line {0} and character {1}.': '转到第 {0} 行第 {1} 列。',
  'Go to line {0}.': '转到第 {0} 行。',
  'Current Line: {0}, Character: {1}. Type a line number between 1 and {2} to navigate to.':
    '当前行: {0}，字符: {1}。输入 1 到 {2} 之间的行号以跳转。',
  'Current Line: {0}, Character: {1}. Type a line number to navigate to.':
    '当前行: {0}，字符: {1}。输入行号以跳转。',
  'Please type a number between 1 and {0}': '请输入 1 到 {0} 之间的数字',
  'Open a text editor first to go to a line.': '请先打开文本编辑器再跳转到行。',

  // ===== 右键菜单 / 剪贴板 =====
  Undo: '撤销',
  Redo: '重做',
  Cut: '剪切',
  Copy: '复制',
  Paste: '粘贴',
  'Copy As': '复制为',
  'Copy With Syntax Highlighting': '带语法高亮复制',
  'Paste As...': '粘贴为…',
  'Paste as Text': '粘贴为文本',
  'Select All': '全选',
  'Select Editor': '选择编辑器',
  'Show Editor Context Menu': '显示编辑器上下文菜单',
  'Change All Occurrences': '更改所有出现项',
  Share: '分享',
  'More Actions...': '更多操作…',
  Move: '移动',
  'Move Selected Text Left': '将选定文本左移',
  'Move Selected Text Right': '将选定文本右移',
  'Select Paste Action': '选择粘贴操作',
  'Show paste options...': '显示粘贴选项…',
  'Show drop options...': '显示拖放选项…',
  'Running paste handlers': '正在运行粘贴处理程序',
  'Resolving paste edit. Click to cancel': '正在解析粘贴编辑。点击取消',
  'Running paste handlers. Click to cancel and do basic paste': '正在运行粘贴处理程序。点击取消并执行基本粘贴',
  'Running drop handlers. Click to cancel': '正在运行拖放处理程序。点击取消',
  "No paste edits for '{0}' found": '未找到“{0}”的粘贴编辑',
  'Insert Plain Text': '插入纯文本',
  'Insert HTML': '插入 HTML',
  'Insert Uri': '插入 URI',
  'Insert Uris': '插入 URI(多个)',
  'Insert Path': '插入路径',
  'Insert Paths': '插入路径(多个)',
  'Insert Relative Path': '插入相对路径',
  'Insert Relative Paths': '插入相对路径(多个)',
  'Cannot edit in read-only editor': '无法在只读编辑器中编辑',
  'Cannot edit in read-only input': '无法在只读输入框中编辑',

  // ===== 命令面板 / 快速输入 =====
  'Command Palette': '命令面板',
  'Show And Run Commands': '显示并运行命令',
  'Show all Quick Access Providers': '显示所有快速访问提供程序',
  'Select a command': '选择命令',
  'Execute Command': '执行命令',
  'Execute command': '执行命令',
  'Execute command {0}': '执行命令 {0}',
  "Click to execute command '{0}'": "点击执行命令 '{0}'",
  "Command '{0}' resulted in an error": "命令 '{0}' 出错",
  'Run: {0}': '运行: {0}',
  'Type to search': '输入以搜索',
  'Type to filter': '输入以筛选',
  'Type to narrow down results.': '输入以缩小结果范围。',
  'Quick Input': '快速输入',
  "Press 'Enter' to confirm your input or 'Escape' to cancel": '按 Enter 确认输入，或按 Esc 取消',
  'commonly used': '常用',
  'recently used': '最近使用',
  'other commands': '其他命令',
  'similar commands': '相似命令',
  OK: '确定',
  Cancel: '取消',
  Close: '关闭',
  Ignore: '忽略',
  Back: '上一步',
  'Back ({0})': '上一步 ({0})',
  Custom: '自定义',
  Workbench: '工作台',
  'Toggle all checkboxes': '切换所有复选框',
  'Filter elements when searching.': '搜索时筛选元素。',
  'Filter keyboard navigation will filter out and hide all the elements which do not match the keyboard input.':
    '筛选式键盘导航会筛除并隐藏与键盘输入不匹配的所有元素。',
  'Highlight elements when searching. Further up and down navigation will traverse only the highlighted elements.':
    '搜索时高亮元素。之后上下导航将只在被高亮的元素间遍历。',
  'Highlight keyboard navigation highlights elements which match the keyboard input. Further up and down navigation will traverse only the highlighted elements.':
    '高亮式键盘导航会高亮与键盘输入匹配的元素。之后上下导航将只在被高亮的元素间遍历。',
  'Simple keyboard navigation focuses elements which match the keyboard input. Matching is done only on prefixes.':
    '简单键盘导航聚焦与键盘输入匹配的元素。仅按前缀匹配。',
  'Use contiguous matching when searching.': '搜索时使用连续匹配。',
  'Use fuzzy matching when searching.': '搜索时使用模糊匹配。',

  // ===== 注释 =====
  'Toggle Line Comment': '切换行注释',
  'Add Line Comment': '添加行注释',
  'Remove Line Comment': '移除行注释',
  'Toggle Block Comment': '切换块注释',

  // ===== 行操作 / 多光标 =====
  'Copy Line Up': '向上复制行',
  'Copy Line Down': '向下复制行',
  'Move Line Up': '上移行',
  'Move Line Down': '下移行',
  'Insert Line Above': '在上方插入行',
  'Insert Line Below': '在下方插入行',
  'Delete Line': '删除行',
  'Delete All Left': '删除左侧全部',
  'Delete All Right': '删除右侧全部',
  'Delete Word': '删除词',
  'Delete Duplicate Lines': '删除重复行',
  'Join Lines': '合并行',
  'Transpose Characters around the Cursor': '转置光标周围字符',
  'Transpose Letters': '转置字母',
  'Sort Lines Ascending': '按升序排列行',
  'Sort Lines Descending': '按降序排列行',
  'Trim Trailing Whitespace': '清除行尾空白',
  'Transform to Uppercase': '转换为大写',
  'Transform to Lowercase': '转换为小写',
  'Transform to Title Case': '转换为标题式大小写',
  'Transform to Camel Case': '转换为驼峰命名',
  'Transform to Pascal Case': '转换为帕斯卡命名',
  'Transform to Snake Case': '转换为蛇形命名',
  'Transform to Kebab Case': '转换为短横线命名',
  'Replace with Next Value': '替换为下一个值',
  'Replace with Previous Value': '替换为上一个值',
  'Add Cursor Above': '在上方添加光标',
  'Add Cursor Below': '在下方添加光标',
  'Add Cursors To Bottom': '在底部添加光标',
  'Add Cursors To Top': '在顶部添加光标',
  'Add Cursors to Line Ends': '在行尾添加光标',
  'Add Selection To Next Find Match': '添加下一个匹配到选定内容',
  'Add Selection To Previous Find Match': '添加上一个匹配到选定内容',
  'Move Last Selection To Next Find Match': '将最后选定内容移至下一个匹配',
  'Move Last Selection To Previous Find Match': '将最后选定内容移至上一个匹配',
  'Select All Occurrences of Find Match': '选择所有查找匹配项',
  'Expand Selection': '扩大选择范围',
  'Shrink Selection': '缩小选择范围',
  'Expand Line Selection': '扩展行选定范围',
  'Focus Next Cursor': '聚焦下一个光标',
  'Focus Previous Cursor': '聚焦上一个光标',
  'Focuses the next cursor': '聚焦下一个光标',
  'Focuses the previous cursor': '聚焦上一个光标',
  'Cursor Undo': '光标撤销',
  'Cursor Redo': '光标重做',
  'Cursor added: {0}': '已添加 {0} 个光标',
  'Cursors added: {0}': '已添加 {0} 个光标',
  'Removed secondary cursors': '已移除次要光标',
  'Increase Multi Cursor Limit': '增加多光标上限',
  'The number of cursors has been limited to {0}. Consider using [find and replace](https://code.visualstudio.com/docs/editor/codebasics#_find-and-replace) for larger changes or increase the editor multi cursor limit setting.':
    '光标数已限制为 {0}。更大改动可使用[查找和替换](https://code.visualstudio.com/docs/editor/codebasics#_find-and-replace)，或调大编辑器多光标上限设置。',
  'Duplicate Selection': '重复选定内容',

  // ===== 折叠 =====
  Fold: '折叠',
  Unfold: '展开',
  'Fold All': '全部折叠',
  'Unfold All': '全部展开',
  'Fold Recursively': '逐层折叠',
  'Unfold Recursively': '逐层展开',
  'Fold All Block Comments': '折叠所有块注释',
  'Fold All Regions': '折叠所有区域',
  'Unfold All Regions': '展开所有区域',
  'Fold All Except Selected': '折叠除所选外的全部',
  'Unfold All Except Selected': '展开除所选外的全部',
  'Fold Level {0}': '折叠级别 {0}',
  'Toggle Fold': '切换折叠',
  'Toggle Fold Recursively': '切换逐层折叠',
  'Go to Next Folding Range': '转到下一个折叠区域',
  'Go to Previous Folding Range': '转到上一个折叠区域',
  'Go to Parent Fold': '转到父级折叠',
  'Create Folding Range from Selection': '从选定内容创建折叠区域',
  'Remove Manual Folding Ranges': '移除手动折叠区域',
  'Click to expand the range.': '点击展开该区域。',
  'Click to collapse the range.': '点击折叠该区域。',

  // ===== 重命名 =====
  'Rename Symbol': '重命名符号',
  'No result.': '无结果。',
  'Received {0} rename suggestions': '收到 {0} 个重命名建议',
  'Renaming {0} to {1}': '正在将 {0} 重命名为 {1}',
  "Renaming '{0}' to '{1}'": "正在将 '{0}' 重命名为 '{1}'",
  "Successfully renamed '{0}' to '{1}'. Summary: {2}": "已成功将 '{0}' 重命名为 '{1}'。摘要: {2}",
  'Rename failed to apply edits': '重命名无法应用编辑',
  'Rename failed to compute edits': '重命名无法计算编辑',
  'Rename input. Type new name and press Enter to commit.': '重命名输入。输入新名称并按回车确认。',
  'Focus Next Rename Suggestion': '聚焦下一个重命名建议',
  'Focus Previous Rename Suggestion': '聚焦上一个重命名建议',
  'Generate new name suggestions': '生成新名称建议',
  'An unknown error occurred while resolving rename location': '解析重命名位置时发生未知错误',
  'Start Linked Editing': '开始链接编辑',

  // ===== 格式化 / 缩进 =====
  'Format Document': '格式化文档',
  'Format Selection': '格式化选定内容',
  'Convert Indentation to Spaces': '将缩进转换为空格',
  'Convert Indentation to Tabs': '将缩进转换为制表符',
  'Convert the spaces indentation to tabs.': '将空格缩进转换为制表符。',
  'Convert the tab indentation to spaces.': '将制表符缩进转换为空格。',
  'Indent Using Spaces': '使用空格缩进',
  'Indent Using Tabs': '使用制表符缩进',
  'Use indentation with spaces.': '使用空格缩进。',
  'Use indentation with tabs.': '使用制表符缩进。',
  'Change Tab Display Size': '更改制表符显示宽度',
  'Change the space size equivalent of the tab.': '更改制表符等效的空格数。',
  'Current Tab Size': '当前制表符宽度',
  'Default Tab Size': '默认制表符宽度',
  'Configured Tab Size': '配置的制表符宽度',
  'Detect Indentation from Content': '从内容检测缩进',
  'Detect the indentation from content.': '从内容检测缩进。',
  'Indent Line': '增加行缩进',
  'Outdent Line': '减少行缩进',
  'Reindent Lines': '重新缩进行',
  'Reindent Selected Lines': '重新缩进选定行',
  'Reindent the lines of the editor.': '重新缩进编辑器的行。',
  'Reindent the selected lines of the editor.': '重新缩进编辑器的选定行。',
  'Pressing Tab will now insert the tab character': '按 Tab 现在将插入制表符',
  'Pressing Tab will now move focus to the next focusable element': '按 Tab 现在将焦点移至下一个可聚焦元素',
  'Determines whether the tab key moves focus around the workbench or inserts the tab character in the current editor. This is also called tab trapping, tab navigation, or tab focus mode.':
    '确定 Tab 键是在界面元素间移动焦点还是在当前编辑器中插入制表符。这也称为 Tab 捕获、Tab 导航或 Tab 焦点模式。',

  // ===== 编辑器字号 / 片段占位符 / 杂项(第二轮补) =====
  'Increase Editor Font Size': '放大编辑器字号',
  'Decrease Editor Font Size': '缩小编辑器字号',
  'Reset Editor Font Size': '重置编辑器字号',
  'Go to next placeholder...': '转到下一个占位符…',
  'Hide Disabled': '隐藏已禁用项',
  'Show Disabled': '显示已禁用项',
  'No elements found.': '未找到元素。',
  "No results for '{0}'": '无“{0}”的结果',
  'Remove Brackets': '移除括号',
  'Show the definition preview hover in the editor.': '显示编辑器中的定义预览悬停。',

  // ===== 粘滞滚动 / 杂项命令 =====
  'Sticky Scroll': '粘滞滚动',
  'Toggle Editor Sticky Scroll': '切换编辑器粘滞滚动',
  'Toggle/enable the editor sticky scroll which shows the nested scopes at the top of the viewport':
    '切换/启用编辑器粘滞滚动，在视口顶部显示嵌套作用域',
  'Focus on the editor sticky scroll': '聚焦编辑器粘滞滚动',
  'Go to the focused sticky scroll line': '转到聚焦的粘滞滚动行',
  'Select the next editor sticky scroll line': '选择下一个粘滞滚动行',
  'Select the previous sticky scroll line': '选择上一个粘滞滚动行',
  'Stick to the end even when going to longer lines': '即使转到更长的行也固定在末尾',
  'Show CodeLens Commands For Current Line': '显示当前行的 CodeLens 命令',
  'Developer: Force Retokenize': '开发者: 强制重新分词',
  'Developer: Inspect Tokens': '开发者: 检查 Token',
  'Toggle High Contrast Theme': '切换高对比度主题',
  'Editor content': '编辑器内容',
  'Made {0} edits in {1} files': '在 {1} 个文件中进行了 {0} 处编辑',
  Minimap: '缩略图',
  'Render Characters': '渲染字符',
  Proportional: '等比',
  Fit: '适应',
  Slider: '滑块',
  Unbound: '未绑定',
  Always: '总是',
  'Adjust settings': '调整设置',
  'Double-click to insert': '双击以插入',
  Filter: '筛选',
  Next: '下一个',
  Previous: '上一个',
  'Cleared Input': '已清除输入',

  // ===== 颜色选择器 =====
  'Click to toggle color options (rgb/hsl/hex)': '点击切换颜色选项 (rgb/hsl/hex)',
  'Show or Focus Standalone Color Picker': '显示或聚焦独立颜色选择器',
  'Show or focus a standalone color picker which uses the default color provider. It displays hex/rgb/hsl colors.':
    '显示或聚焦使用默认颜色提供程序的独立颜色选择器。它显示 hex/rgb/hsl 颜色。',
  'Insert hex/rgb/hsl colors with the focused standalone color picker.': '使用聚焦的独立颜色选择器插入 hex/rgb/hsl 颜色。',
  'Hide the standalone color picker.': '隐藏独立颜色选择器。',

  // ===== Unicode 高亮 =====
  'Configure Unicode Highlight Options': '配置 Unicode 高亮选项',
  'The character {0} could be confused with the ASCII character {1}, which is more common in source code.':
    '字符 {0} 可能与 ASCII 字符 {1} 混淆，后者在源代码中更常见。',
  'The character {0} could be confused with the character {1}, which is more common in source code.':
    '字符 {0} 可能与字符 {1} 混淆，后者在源代码中更常见。',
  'The character {0} is invisible.': '字符 {0} 是不可见字符。',
  'The character {0} is not a basic ASCII character.': '字符 {0} 不是基本 ASCII 字符。',
  'This document contains many ambiguous unicode characters': '此文档包含大量易混淆的 Unicode 字符',
  'This document contains many invisible unicode characters': '此文档包含大量不可见的 Unicode 字符',
  'This document contains many non-basic ASCII unicode characters': '此文档包含大量非基本 ASCII 的 Unicode 字符',
  'Disable Ambiguous Highlight': '禁用易混淆字符高亮',
  'Disable Highlight In Comments': '禁用注释中字符高亮',
  'Disable Highlight In Strings': '禁用字符串中字符高亮',
  'Disable Invisible Highlight': '禁用不可见字符高亮',
  'Disable Non ASCII Highlight': '禁用非 ASCII 高亮',
  'Disable highlighting of ambiguous characters': '禁用易混淆字符的高亮',
  'Disable highlighting of characters in comments': '禁用注释中字符的高亮',
  'Disable highlighting of characters in strings': '禁用字符串中字符的高亮',
  'Disable highlighting of invisible characters': '禁用不可见字符的高亮',
  'Disable highlighting of non basic ASCII characters': '禁用非基本 ASCII 字符的高亮',
  'Allow unicode characters that are more common in the language "{0}".': '允许语言“{0}”中更常见的 Unicode 字符。',
  'Exclude {0} (invisible character) from being highlighted': '将 {0}(不可见字符)排除在高亮之外',
  'Exclude {0} from being highlighted': '将 {0} 排除在高亮之外',
  'Show Exclude Options': '显示排除选项',

  // ===== 行终止符 / 链接 =====
  'Detected unusual line terminators': '检测到异常行终止符',
  'Unusual Line Terminators': '异常行终止符',
  "The file '{0}' contains one or more unusual line terminator characters, like Line Separator (LS) or Paragraph Separator (PS).\n\nIt is recommended to remove them from the file. This can be configured via `editor.unusualLineTerminators`.":
    '文件“{0}”包含一个或多个异常行终止符(如行分隔符 LS 或段落分隔符 PS)。\n\n建议从文件中移除它们。可通过 `editor.unusualLineTerminators` 配置。',
  'Follow link': '跟随链接',
  'Open Link': '打开链接',
  'Failed to open this link because it is not well-formed: {0}': '无法打开此链接，格式不正确: {0}',
  'Failed to open this link because its target is missing.': '无法打开此链接，目标缺失。',

  // ===== 选择锚点 =====
  'Set Selection Anchor': '设置选择锚点',
  'Go to Selection Anchor': '转到选择锚点',
  'Select from Anchor to Cursor': '选择从锚点到光标',
  'Cancel Selection Anchor': '取消选择锚点',
  'Selection Anchor': '选择锚点',
  'Anchor set at {0}:{1}': '锚点已设置于 {0}:{1}',

  // ===== 大文档提示 =====
  'Rendering paused for long line for performance reasons. This can be configured via `editor.stopRenderingLineAfter`.':
    '长行已暂停渲染以保证性能。可通过 `editor.stopRenderingLineAfter` 配置。',
  'Tokenization is skipped for long lines for performance reasons. This can be configured via `editor.maxTokenizationLineLength`.':
    '长行已跳过分词以保证性能。可通过 `editor.maxTokenizationLineLength` 配置。',

  // ===== 月份 / 星期(组件内日期) =====
  January: '一月', February: '二月', March: '三月', April: '四月', May: '五月',
  June: '六月', July: '七月', August: '八月', September: '九月', October: '十月',
  November: '十一月', December: '十二月',
  Jan: '1月', Feb: '2月', Mar: '3月', Apr: '4月', Jun: '6月', Jul: '7月',
  Aug: '8月', Sep: '9月', Oct: '10月', Nov: '11月', Dec: '12月',
  Monday: '星期一', Tuesday: '星期二', Wednesday: '星期三', Thursday: '星期四',
  Friday: '星期五', Saturday: '星期六', Sunday: '星期日',
  Mon: '周一', Tue: '周二', Wed: '周三', Thu: '周四', Fri: '周五', Sat: '周六', Sun: '周日',
};
